Magazin/Magazin/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
<<<<<<< HEAD
    path('reader/', include('Reader.urls')),  
    path('login/', include('Login.urls')),
    path('writer/', include('Writer.urls')),
    path('dashboard/', include('Dashboard.urls')),
    path('',include('Main.urls'))
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
=======
    path('login/', include('Login.urls')),
    path('writer/', include('Writer.urls')),
    # Diğer URL yönlendirmeleri
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
>>>>>>> 1d8751b32b848d62d38b9f37978c5b742c64354b

Magazin/Main/urls.py
from django.urls import path
from django.conf.urls.static import static
from .views import *


urlpatterns = [
    path('', index, name='Main/base'),
    path('blog/', blog, name='Main/blog'),
    path('blog_category/', blog_category, name='Main/blog-category'),
    path('fashion/', fashion, name='Main/fashion'),
    path('lifestyle/', lifestyle, name='Main/lifestyle'),
    path('travel/', travel, name='Main/travel'),
    path('post_single/', post_single, name='Main/post-single'),
]

Magazin/Writer/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import *

urlpatterns = [
    path('', base, name='Writer/base.html'),  # Root URL handled by Reader app
    path('create/',create_post, name='create_post'),   
    path('', post_list, name='post_list'),  # Burada post_list isimli bir URL tanımlanıyor
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Magazin/Login/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField  # Using ckeditor.fields for Rich Text Editor
from django.utils.text import slugify

class Reader(models.Model):
    user = models.ForeignKey(User, verbose_name="Kullanıcı", on_delete=models.SET_NULL, null=True)
    phone = models.CharField(max_length=20, null=True, blank=True)
    is_darkmode = models.BooleanField(verbose_name="Dark Mode", default=False)
    created_date = models.DateTimeField(verbose_name="Oluşturma Tarihi", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="Son Güncelleme Tarihi", auto_now=True)

    is_delete = models.BooleanField(verbose_name="Silindi", default=False)
    delete_date = models.DateTimeField(verbose_name="Silinme Tarihi", blank=True, null=True)
    slug = models.SlugField(verbose_name="Url", unique=True)

    def __str__(self):
        if self.user.first_name and self.user.last_name:
            return f"{self.user.first_name} {self.user.last_name}"
        else:
            return self.user.username
        
    def save(self, *args, **kwargs):
        if not self.slug:
            full_name = f"{self.user.first_name} {self.user.last_name}".replace('ı', 'i')
            proposed_slug = slugify(full_name)
            if Reader.objects.filter(slug=proposed_slug).exists():
                counter = 1
                while True:
                    new_slug = f"{proposed_slug}-{counter}"
                    if not Reader.objects.filter(slug=new_slug).exists():
                        proposed_slug = new_slug
                        break
                    counter += 1
            self.slug = proposed_slug
        super().save(*args, **kwargs)

class Writer(models.Model):
    user = models.ForeignKey(User, verbose_name="Kullanıcı", on_delete=models.SET_NULL, null=True, related_name= 'writers')
    phone = models.CharField(max_length=20, null=True, blank=True)
    is_darkmode = models.BooleanField(verbose_name="Dark Mode", default=False)
    is_delete = models.BooleanField(verbose_name="Silindi", default=False)
    delete_date = models.DateTimeField(verbose_name="Silinme Tarihi", blank=True, null=True)
    created_date = models.DateTimeField(verbose_name="Oluşturma Tarihi", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="Son Güncelleme Tarihi", auto_now=True)
    slug = models.SlugField(verbose_name="Url", unique=True, editable=False)
    bio = models.TextField(verbose_name=("Biyografi"), blank=True, null=True)

    def __str__(self):
        if self.user.first_name and self.user.last_name:
            return f"{self.user.first_name} {self.user.last_name}"
        else:
            return self.user.username
        
    def save(self, *args, **kwargs):
        if not self.slug:
            full_name = f"{self.user.first_name} {self.user.last_name}"
            proposed_slug = slugify(full_name)
            if Writer.objects.filter(slug=proposed_slug).exists():
                counter = 1
                while True:
                    new_slug = f"{proposed_slug}-{counter}"
                    if not Writer.objects.filter(slug=new_slug).exists():
                        proposed_slug = new_slug
                        break
                    counter += 1
            self.slug = proposed_slug
        super().save(*args, **kwargs)

class Article(models.Model):
    title = models.CharField(verbose_name="Başlık", max_length=100)
    content = RichTextField(verbose_name="İçerik")
    writer = models.ForeignKey(Writer, verbose_name="Yazar", on_delete=models.CASCADE)
    created_date = models.DateTimeField(verbose_name="Oluşturma Tarihi", auto_now_add=True)
    updated_date = models.DateTimeField(verbose_name="Son Güncelleme Tarihi", auto_now=True)
    is_delete = models.BooleanField(verbose_name="Silindi", default=False)
    delete_date = models.DateTimeField(verbose_name="Silinme Tarihi", blank=True, null=True)
    slug = models.SlugField(verbose_name="Url", unique=True, editable=False)

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            proposed_slug = slugify(self.title)
            if Article.objects.filter(slug=proposed_slug).exists():
                counter = 1
                while True:
                    new_slug = f"{proposed_slug}-{counter}"
                    if not Article.objects.filter(slug=new_slug).exists():
                        proposed_slug = new_slug
                        break
                    counter += 1
            self.slug = proposed_slug
        super().save(*args, **kwargs)

class ArticleComment(models.Model):
    article = models.ForeignKey(Article, verbose_name="Makale", on_delete=models.CASCADE, related_name='comments')
    reader = models.ForeignKey(Reader, verbose_name="Okuyucu", on_delete=models.SET_NULL, null=True)
    content = models.TextField(verbose_name="Yorum")
    created_date = models.DateTimeField(verbose_name="Oluşturma Tarihi", auto_now_add=True)
    is_delete = models.BooleanField(verbose_name="Silindi", default=False)
    delete_date = models.DateTimeField(verbose_name="Silinme Tarihi", blank=True, null=True)

    def __str__(self):
        return f"{self.reader.user.username} - {self.article.title}"

class UserLog(models.Model):
    user = models.ForeignKey(User, verbose_name="Kullanıcı", on_delete=models.SET_NULL, null=True)
    action = models.CharField(verbose_name="İşlem", max_length=1024)
    created_date = models.DateTimeField(verbose_name="Oluşturma Tarihi", auto_now_add=True)

    def __str__(self):
        if self.user.first_name and self.user.last_name:
            return f"{self.user.first_name} {self.user.last_name} Logları"
        else:
            return f"{self.user.username} Logları"

Magazin/Writer/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Post(models.Model):
    title = models.CharField(max_length=200)
    content = RichTextField()  # Using RichTextField for the content
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        return self.title

Magazin/Writer/forms.py
# forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content', 'image']

Magazin/Writer/views.py
from django.shortcuts import render, redirect
from .models import Post
from .forms import PostForm



def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('post_list')  # Replace 'post_list' with the name of your post list view
    else:
        form = PostForm()
    return render(request, 'Writer/create_post.html', {'form': form})

# Create your views here.
def base(request):
    return render(request, 'Writer/base.html')



def post_list(request):
    posts = Post.objects.all()
    return render(request, 'Writer/base.html', {'posts': posts})

Magazin/Writer/templates/Writer/base.html
{% block content %}
  <h1>Post List</h1>
  <ul>
    {% for post in posts %}
      <li>{{ form.title }}</li>
    {% endfor %}
  </ul>
{% endblock %}

Magazin/Writer/templates/Writer/create_post.html
<!DOCTYPE html>
{% load static %}
<html class="no-js" lang="en">
  <head>
    <!-- Meta Data -->
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Create a New Post - Beatrix</title>
    <meta name="robots" content="noindex, follow" />
    <meta name="description" content />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'assets/media/favicon.png' %}" />
    <!-- Vendors CSS -->
    <link rel="stylesheet" href="{% static 'assets/css/vendor/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/font-awesome.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/icon-font.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/vendor/remixicon.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
    <!-- Site Stylesheet -->
    <!-- <link rel="stylesheet" href="{% static 'assets/css/app.css' %}"> -->
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}" />
    <link rel="stylesheet" href="{% static 'css/create.css' %}" />
  </head>
  <body>
    {% block content %}
      <div class="post-single-area mt-60">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 single-blog-content">
              <div class="post-single-wrapper">
                <!-- Title and Category -->
                <h1 class="post-title">Create a New Post</h1>

                <!-- Form to Create Content -->
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <!-- Input Fields -->
                  <div class="form-group">
                    <label for="id_title">Post Title</label>
                    {{ form.title }}
                  </div>
                  <div class="form-group">
                    <label for="id_content">Post Content</label>
                    {{ form.content }}
                  </div>
                  <!-- Image Upload -->
                  <div class="form-group">
                    <label for="id_image">Upload Image</label>
                    {{ form.image }}
                    <small class="form-text text-muted">Max file size: 5MB. Allowed formats: JPG, PNG.</small>
                  </div>

                  <!-- Submit Button -->
                  <div class="form-group">
                    <button type="submit" class="btn btn-primary">Create Post</button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- CKEditor initialization -->
      <script src="https://cdn.ckeditor.com/4.16.0/standard/ckeditor.js"></script>
      <script>
        CKEDITOR.replace('id_content')
      </script>
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <!-- Jquery JS -->
    <script src="{% static 'assets/js/vendor/jquery-3.6.0.min.js' %}"></script>
    <!-- Vendors JS -->
    <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/imagesloaded.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/odometer.min.js' %}"></script>
    <script src="{% static 'assets/js/vendor/jquery-appear.js' %}"></script>
    <!-- Main JS -->
    <script src="{% static 'assets/js/app.js' %}"></script>
  </body>
</html>